# Generated by Django 5.0.6 on 2024-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Top Wear', 'Top Wear'), ('Bottom Wear', 'Bottom Wear')], max_length=50, null=True),
        ),
    ]
