# Generated by Django 5.0.6 on 2024-09-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_rename_product_addtocart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='products',
            new_name='product',
        ),
    ]
